title: Tarannom Haque # your name (or website title) here
logo: "/images/E9C08DC7-E0DA-482A-8DDD-35E512EE8987_1_201_a.jpeg? raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  
  <br> Data Analyst<br>
   Passionate and driven data analyst with a background in sociology, data analytics, 
   customer experience, and IT. Proficient in R, Python, Excel, SQL, and Tableau, I am dedicated 
   to extracting actionable insights from intricate datasets to empower data-driven decisions. 
   Eager to apply my versatile skills in a dynamic environment, contributing to transformative outcomes.<br><br>

  <a href="https://www.linkedin.com/in/tarannom-haque/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
